import { cookies } from "next/headers";
import type { Metadata } from "next";
import { Sparkles } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { getTranslation } from "@/lib/translations";
import GoogleMapClient from "./GoogleMapClient";
import { fetchContributionClusters, reanalyzeClustersWithGemini } from "./actions";
import { getSession } from "@/lib/session";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Ecosystem Contribution Map | Thailand Humanoid Atlas",
  description: "Geospatial visualization and AI-clustered mapping of humanoid robotics research, development, and inventories across Thailand",
  alternates: { canonical: "/map" },
  openGraph: {
    title: "Ecosystem Contribution Map | Thailand Humanoid Atlas",
    description: "Geospatial visualization and AI-clustered mapping of humanoid robotics research, development, and inventories across Thailand",
    url: "/map",
    siteName: "Thailand Humanoid Atlas",
    images: [
      {
        url: "/logo.png",
        width: 512,
        height: 512,
        alt: "Thailand Humanoid Atlas Logo"
      }
    ],
    locale: "en_US",
    type: "website"
  },
  twitter: {
    card: "summary_large_image",
    title: "Ecosystem Contribution Map | Thailand Humanoid Atlas",
    description: "Geospatial visualization and AI-clustered mapping of humanoid robotics research, development, and inventories across Thailand",
    images: ["/logo.png"]
  }
};const localT = {
  en: {
    clustersStat: "Ecosystem Clusters",
    analyzedStat: "Database Items Analyzed",
    geolocatedStat: "Geolocated Entities",
    engineStat: "Analysis Engine",
    noticeText: "This page uses Gemini AI to analyze all humanoid robotics development, contributions, and inventories in the database to cluster them by organization and geolocate them within Thailand.",
    buttonText: "Trigger Gemini AI Ecosystem Analysis",
    buttonMuted: "Reads all contributions, robot models, and inventories to find new clusters on the map.",
    thHeaderCluster: "Cluster / Institution",
    thHeaderLocation: "Location",
    thHeaderType: "Type",
    thHeaderRecords: "Records",
    thHeaderSummary: "Ecosystem Summary",
    itemsPrefix: "Items:",
    emptyState: "No ecosystem clusters analyzed yet. An administrator can run the AI analysis.",
    analysisFailed: "AI analysis failed (missing/invalid GEMINI_API_KEY or API error). Nothing was written; previous results are unchanged.",
    stalePlaceholder: "Previously cached clusters were hardcoded placeholders, not analysed data, so they are hidden. Run a new analysis to replace them.",
    dbError: "Could not read cached clusters from the database."
  },
  th: {
    clustersStat: "คลัสเตอร์ระบบนิเวศ",
    analyzedStat: "วิเคราะห์ข้อมูลดิบรวม",
    geolocatedStat: "พิกัดหน่วยงานทั้งหมด",
    engineStat: "เครื่องมือวิเคราะห์ AI",
    noticeText: "หน้านี้ใช้เทคโนโลยี Gemini AI เพื่อประมวลผลความสัมพันธ์ของผลงานวิจัย โครงการพัฒนา และข้อมูลคลังหุ่นยนต์ทั้งหมดในระบบ เพื่อจัดคลัสเตอร์แยกตามหน่วยงานสถาบันต่างๆ ในประเทศไทย",
    buttonText: "เริ่มต้นการวิเคราะห์ระบบนิเวศด้วย Gemini AI",
    buttonMuted: "วิเคราะห์ผลงานวิจัย คลัง และผลงานทั้งหมดเพื่อค้นหาคลัสเตอร์ใหม่บนแผนที่",
    thHeaderCluster: "คลัสเตอร์ / สถาบัน",
    thHeaderLocation: "สถานที่ตั้ง",
    thHeaderType: "ประเภท",
    thHeaderRecords: "จำนวนรายการ",
    thHeaderSummary: "สรุปภาพรวมระบบนิเวศ",
    itemsPrefix: "รายการย่อย:",
    emptyState: "ยังไม่มีข้อมูลคลัสเตอร์ที่ถูกวิเคราะห์ ผู้ดูแลระบบสามารถสั่งวิเคราะห์ด้วย AI ได้",
    analysisFailed: "การวิเคราะห์ด้วย AI ล้มเหลว (ไม่มี/ผิด GEMINI_API_KEY หรือ API ขัดข้อง) ระบบไม่ได้เขียนข้อมูลใด ๆ ผลเดิมยังอยู่",
    stalePlaceholder: "คลัสเตอร์ที่แคชไว้ก่อนหน้าเป็นข้อมูลที่เขียนไว้ในโค้ด ไม่ใช่ผลวิเคราะห์ จึงถูกซ่อน กรุณาสั่งวิเคราะห์ใหม่",
    dbError: "อ่านข้อมูลคลัสเตอร์จากฐานข้อมูลไม่ได้"
  }
};

export default async function MapPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const params = await searchParams;
  const cookieStore = await cookies();
  const isAdmin = (await getSession())?.role === "ADMIN";
  const lang = (cookieStore.get("lang")?.value || "en") as "en" | "th";
  const t = getTranslation(lang);

  // 1. Fetch geolocated contribution clusters (cache or dynamically generated by Gemini)
  // B4: cache only; returns a status instead of silently substituting invented data.
  const { clusters, status } = await fetchContributionClusters();
  const statusMessage =
    params.error === "analysis_failed" ? localT[lang].analysisFailed
    : status === "stale_placeholder_ignored" ? localT[lang].stalePlaceholder
    : status === "db_error" ? localT[lang].dbError
    : null;

  // 2. Fetch total raw database records analyzed
  const [contributionCount, robotCount, inventoryCount] = await Promise.all([
    prisma.contribution.count(),
    prisma.robotModel.count(),
    prisma.ownedInventory.count()
  ]);

  const totalAnalyzed = contributionCount + robotCount + inventoryCount;

  // 3. Count unique geolocated organizations
  const uniqueOrgs = new Set(clusters.map((c) => c.organization));

  const apiKey = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY ?? "";

  return (
    <>
      <div className="topline">
        <div>
          <h1>{t.mapTitle}</h1>
          <p className="muted">{t.mapDesc}</p>
        </div>
      </div>

      <div className="grid" style={{ marginBottom: 12 }}>
        <div className="panel motion-panel">
          <p className="muted" style={{ margin: 0 }}>{localT[lang].clustersStat}</p>
          <div className="stat">{clusters.length}</div>
        </div>
        <div className="panel motion-panel">
          <p className="muted" style={{ margin: 0 }}>{localT[lang].analyzedStat}</p>
          <div className="stat">{totalAnalyzed}</div>
        </div>
        <div className="panel motion-panel">
          <p className="muted" style={{ margin: 0 }}>{localT[lang].geolocatedStat}</p>
          <div className="stat">{uniqueOrgs.size}</div>
        </div>
        <div className="panel motion-panel">
          <p className="muted" style={{ margin: 0 }}>{localT[lang].engineStat}</p>
          <div className="stat" style={{ fontSize: 15, marginTop: 10 }}>{process.env.GEMINI_MODEL || "gemini-1.5-flash"}</div>
        </div>
      </div>

      <div className="notice" style={{ marginBottom: 12 }}>
        {localT[lang].noticeText}
      </div>

      {statusMessage && (
        <div className="notice" role="status" style={{ marginBottom: 12, borderColor: "var(--warning)" }}>
          {statusMessage}
        </div>
      )}

      {/* B1: analysis calls a paid API and writes to the DB, so only admins see the button */}
      {isAdmin && (
      <form action={reanalyzeClustersWithGemini} className="toolbar" style={{ marginTop: 0 }}>
        <button className="primary" type="submit">
          <Sparkles size={16} aria-hidden="true" />
          {localT[lang].buttonText}
        </button>
        <span className="muted">{localT[lang].buttonMuted}</span>
      </form>
      )}

      <GoogleMapClient apiKey={apiKey} points={clusters} lang={lang} />

      <div className="table-wrap" style={{ marginTop: 14 }}>
        <table>
          <thead>
            <tr>
              <th>{localT[lang].thHeaderCluster}</th>
              <th>{localT[lang].thHeaderLocation}</th>
              <th>{localT[lang].thHeaderType}</th>
              <th style={{ textAlign: "center" }}>{localT[lang].thHeaderRecords}</th>
              <th>{localT[lang].thHeaderSummary}</th>
            </tr>
          </thead>
          <tbody>
            {clusters.map((cluster) => (
              <tr key={cluster.id}>
                <td style={{ fontWeight: "700" }}>{cluster.title}</td>
                <td>{cluster.locationLabel}</td>
                <td>
                  <span className="badge" style={{ fontSize: "11px", fontWeight: "600", background: "rgba(74, 124, 89, 0.1)", color: "var(--accent)", borderColor: "rgba(74, 124, 89, 0.2)" }}>{cluster.contributorType}</span>
                </td>
                <td style={{ textAlign: "center", fontWeight: "800" }}>{cluster.contributionCount}</td>
                <td style={{ fontSize: "13px", lineHeight: "1.45" }}>
                  {cluster.summary}
                  <div className="muted" style={{ fontSize: "11px", marginTop: 6 }}>
                    <strong>{localT[lang].itemsPrefix}</strong> {cluster.detailsList.join(", ")}
                  </div>
                </td>
              </tr>
            ))}
            {!clusters.length ? (
              <tr>
                <td colSpan={5} className="empty">
                  {localT[lang].emptyState}
                </td>
              </tr>
            ) : null}
          </tbody>
        </table>
      </div>
    </>
  );
}
